<?php

namespace App\DataFixtures;

final class FrancProjectPlanData
{
    public const PROJECTS = [
        'EVENTO FRANC' => [
            'protocolCode' => 'be-green-my-event',
            'measures' => [
                [
                    'sortOrder' => 8,
                    'name' => 'Prioriza espacios con energía 100% renovable certificada, certificación ambiental (ISO 14001, EMAS) o certificado de eficiencia energética (EPC).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'LUSH lkfjbsdc ñcfkjnbasdc ñdocnasdñvkj ased ghsfghdfhdfh',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 9,
                    'name' => 'Prioriza conexión a red o acumuladores eléctricos de baterías, evitando grupos electrógenos diésel.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'lsiducgsjdc Sdckjsdñckj sdc ÑDSLCKN ñdslckn SÑDLCK  cÑLDC sdñlkc',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 10,
                    'name' => 'Si usas grupos electrógenos, exige combustibles de bajas emisiones (ej. HVO).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'lkjgljk lijuh ljhñoi jñkj ñlkjñlkl jkj lkjkñ kjlfgffgcfg',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 12,
                    'name' => 'Proporciona puntos de conexión eléctrica a los puestos de comida/bebida para que no usen generadores.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => null,
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 13,
                    'name' => 'Usa iluminación LED en escenografía, señalética y stands.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'adhsbsfsfnt gf fg g ggggghg  g ggggggsdfagdsfgfhsthb hn',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 24,
                    'name' => 'Registra el consumo energético total del evento, solicitando la lectura de contador antes y después para aislar el consumo real.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'sbhshnsrthr rtnhrtnerh dtyhetyjetyje mjhvjh vjh kjh kjhg kjh',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 26,
                    'name' => 'Selecciona alojamientos con certificado de sostenibilidad o planes ambientales documentados.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'sdfbsrbrwt dfsrber srtbsrtbrtbrtb sfbtbstrbrwtb sfbrtrbwrtbrt sfbvsbtrbrtb',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 29,
                    'name' => 'Registra las pernoctaciones contratadas por la organización del evento.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => true,
                    'isCritical' => false,
                    'observations' => 'dfbadbb sfgbsgbbr  wsgbwrbwrtbrw wfgbwrtbrwtb wgfbwrtbrt',
                    'actionTaken' => 'rtdfvadababdadbsdtfbstbstbsfbsfbg',
                    'executionIncident' => null,
                    'hasEvidence' => true,
                ],
                [
                    'sortOrder' => 31,
                    'name' => 'Elige el recinto por proximidad a estaciones de transporte público.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => true,
                    'isCritical' => true,
                    'observations' => 'sfbsbrstb w rtbnwrbrwt  wrn rtg rt rt rt rt rt rt rgfssfhgfhbfghgt r',
                    'actionTaken' => 'xfgnfgndfgndfgn  sf fg sg fg fg gf gf fg gf sf f gfffg gf gf fg fsg sfg fsg fg fg fg fg fg',
                    'executionIncident' => null,
                    'hasEvidence' => true,
                ],
                [
                    'sortOrder' => 33,
                    'name' => 'Coordina con el ayuntamiento el refuerzo de transporte público en eventos de aforo masivo, con puntos de autobús lanzadera accesibles y accesos peatonales seguros al recinto.',
                    'isApplicable' => false,
                    'willImplement' => null,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'rsthsrthrt srgnrtnerthghfghfgnfgnfghdfgnfgngbnxgfnxfgnxfgnghn',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 39,
                    'name' => 'Prioriza tren o autobús frente al avión cuando el trayecto alternativo sea razonable (por ejemplo, menos de 6 horas de viaje).',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'adfvadfv adfvafdv asdfdbadb adfvadfvadfbvb xfg xfg xfg gf fxg xfg vx vx v gv',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 40,
                    'name' => 'Prioriza vuelos directos y clase turista frente a escalas o business en los desplazamientos aéreos del evento (talent, ponentes).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'mjhjhgj jñkjñlk jñlkjñlk lkjñklh x bv xvb xb xb gf gf fg gf fxg fxg fxg fxg xfg',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 47,
                    'name' => 'Registra el transporte de mercancía/material pesado, prioriza a los proveedores de proximidad y evalúa su huella.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => false,
                    'isCritical' => true,
                    'observations' => 'liuglukjh ljhlk jhkjlh ñlkj ñlkjñl kjñlkhlkhñlkh ñlkñlklkhñlk hñlklhlkhñlkh ñlkhñlklkñlk ñlkhñlkhlklh lkhkhñlkh ñlkhñlkhñkl lkhñklhklhklñj',
                    'actionTaken' => null,
                    'executionIncident' => 'asdvadfvadf adfv adf adf adf adf adf adf df adf daf adf adf adf adf adf',
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 55,
                    'name' => 'Registra el kilometraje de los asistentes y las emisiones del transporte organizado.',
                    'isApplicable' => false,
                    'willImplement' => null,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'dfagaer afbaerger sergerewrgfghfhfhbwrg ergewrgwergewrg',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 68,
                    'name' => 'Prioriza espacios con montaje estándar preexistente frente a los personalizados a medida, para reducir transporte y material de montaje.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'kjbkj hñlkj lkjjñlkjlkj lkjñlk´lkj ´lkjlk´kj ´lkj´klj´klj ´ñlj´lj´lñ lknkjh luglg hjgkjhg hjghjghj g',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 70,
                    'name' => 'Alquila mobiliario y estructuras en lugar de comprarlos; antes de adquirir equipamiento nuevo, prioriza la segunda mano o materiales sostenibles.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'dfsdfbfg erg wrgwwergwg  wrgw s r tertherthrthrt wg  tgwtr',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 71,
                    'name' => 'Usa estructuras y mobiliario modulares, desmontables y multifunción, con proveedores de stands certificados (madera FSC, aluminio reciclado).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'kglk jhlkjh kjhlkj hlkjhlhg hgkhg khgkjhg ljhgkjhg kjhgjh gkjhg kjh gkjhj gkjh gkjhg kjhg kjhg lkjg ljg lh gj hg hg jhg n',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 72,
                    'name' => 'Diseña la escenografía para reutilizarla en próximas ediciones, reutiliza estructuras de eventos anteriores y haz upcycling de los materiales al finalizar.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'ljhlkjh lkjhñhñjh ñlkhhlkñlkh ñlkhñlkhhgoiyguygoyu giugiug iugiug iuhpuihpiu hioihpihpio hio',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 93,
                    'name' => 'Elabora un plan de gestión de residuos previo al evento, identificando los residuos que se generarán y su manejo.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'jhljk.kj ñlkjñlklñlkhñlk ñlkhñlkhñoih poihoñihoi hoihóih ihóih íh´ikhj´pk j',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 95,
                    'name' => 'Minimiza el plástico de un solo uso en todo el recinto.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'ñlkhñlkh lkhñlkhñlkh ñkhñhlkhñoi hñoihoi ioup iuìou `pouìouìou ìouìouìoìo ihyuyugi giuo oytiu yriuyriu y',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 97,
                    'name' => 'Instala puntos de separación de residuos (orgánico, envases, papel, resto) accesibles y señalizados.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'kjhlhjg kjhlkjh kjhñkjgñkjg ñjgñkjgl kjgkjgkjg ñkjgh',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 101,
                    'name' => 'Habilita puntos de recogida específicos para materiales de escenografía, señalética, cableado y moqueta técnica al desmontar, para su reciclaje o reutilización.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'gfbsnshsrthststr kjh ,jh lkjh lkjhkñjh gl hjjglkjh lkjhljk h',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 102,
                    'name' => 'Dona o redistribuye el material sobrante (decoración, merchandising, mobiliario) tras el evento.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'fsgbsbdsfa adfbafbadfbdf sfbdfbadfbdfbdf adfbdafbdfbdfs',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 104,
                    'name' => 'Registra el peso y tipo de residuos generados por el evento.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'kljhkjhkjh ñkjjhkjhñkjh ñlkkhñlhkj oyutouitiuo piypioypoiy poiypoiy',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 107,
                    'name' => 'Prioriza catering de proximidad y temporada, con certificación de comercio justo o km 0.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'lkjlkjh ñkjhkjkj kjhñjhñh ñklhñklkh lkhnb, nb.mb .m,b.b.b.mbn .mbkjv hfkgfk tuf',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 108,
                    'name' => 'Reduce proteína animal (evitando al máximo la carne roja) combinando con opciones vegetarianas y veganas.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'kgjhg ljhgkjhkjhfk hkhfljhfljhf lh ljhg jhglkhjglhjgkjh glhglhlhg lkjg',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 115,
                    'name' => 'Elimina el plástico de un solo uso en vajilla, cubertería y vasos usando vajilla reutilizable o compostable certificada.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'kjhgjhg lhjgljhgjh hgljgljhl lhghjlhglh glkjglkjg lkjglkglkjgjkg kjglkjglkjglkj glkjglkj gkjglkj glkjg',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 116,
                    'name' => 'Ofrece agua en dispensadores en lugar de botellas individuales, tanto para el público como en backstage/organización. Si se usan botellas de un solo uso, exige R-PET.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'fghdgnfs sfgnsfgnfsgn sfgbsfgnsfgb sfgbfsgbsfg vdfdfg',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 118,
                    'name' => 'Prioriza latas de aluminio frente a vidrio o plástico en bebidas carbonatadas por su mayor reciclabilidad.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'xfgfnsfnfnfgnfg lkj kjb kjh lkhkjlhñlkjh ñlkhlkhñ lkhñlkhlklkj lkjlkjñl kj',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 124,
                    'name' => 'Realiza una evaluación de impacto ambiental si el evento se celebra en un espacio natural protegido.',
                    'isApplicable' => false,
                    'willImplement' => null,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'sfhentyjetyj kjh kj ñlkjñkj ñlk ñlkjñlkjñlk jlkjñ lkjñlkkjñlkj lkñlkjñlk jlkjñlkjlkj',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 131,
                    'name' => 'Obtén el compromiso de sostenibilidad firmado por la dirección u organización del evento.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'zdbsbsdt  abstbstbsthb lk ñlkh lk ñlkljñlkñlkj lkjñlkjñ lkjñlkljñlkjñlkj',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 132,
                    'name' => 'Elabora un Plan de Sostenibilidad antes del evento con medidas a adoptar y objetivos de reducción e implementa las medidas durante el mismo.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => false,
                    'isCritical' => true,
                    'observations' => 'lkjjglkjgh lkjlkjh lkjglkjglkjg lkjg lkjlkjglkjglkjg',
                    'actionTaken' => null,
                    'executionIncident' => 'hgdc,jhf.kjvhvbcjhvjhvkhkv,jhfhjg.kjgjgjg-lg-jlgkñjgñljkhñljgkjgkhglhglkhglkjggjjgkjkg',
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 134,
                    'name' => 'Contrata un/a Eco Manager o responsable de sostenibilidad para el evento, encargado de implementar las medidas y realizar la toma de datos.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => true,
                    'isCritical' => true,
                    'observations' => 'liugñkjhñ ñlkkhñkjhñ ñkjlhjhñlkh  vh c chncghndghndfndghn',
                    'actionTaken' => 'dndghdghmdghmdghmgfmcvbdbdfbsdbsdfsfgnsfgnfsg',
                    'executionIncident' => null,
                    'hasEvidence' => true,
                ],
                [
                    'sortOrder' => 136,
                    'name' => 'Exige a proveedores y expositores su política de sostenibilidad mediante una guía obligatoria de buenas prácticas.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => ',hvkjkj.kjkjlh ´lkjlkljlkjlkkñlhñlk ñlkhñlkb x v chgnghmghmgh',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 137,
                    'name' => 'Aplica a certificaciones de sostenibilidad de eventos disponibles en el mercado (ISO 20121, sellos de recinto sostenible, etc.).',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'fgbsfbsgfbb fgnfsgbsfn dfggndghndgh dgh thn dtyndtyhntdfgbnfgnfgn',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 138,
                    'name' => 'Comunica internamente al personal y voluntariado los criterios y objetivos de sostenibilidad del evento antes de su celebración.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'vbbn mgh dghndghndgh dhn dgh dgh gh b gbnfgnfsgnsfgnsfgnf gf sfg sfg fsg fs',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 139,
                    'name' => 'Comunica de forma clara las opciones de transporte sostenible en todos los canales de confirmación de asistencia.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => true,
                    'isCritical' => true,
                    'observations' => 'gfbndfnfgn sfgbsgfbsf  sfgb sfgn fsgnbgfnfgngfndfgnfg',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => true,
                ],
                [
                    'sortOrder' => 145,
                    'name' => 'Encuesta a los asistentes sobre su medio de transporte y distancia recorrida para calcular las emisiones de CO2, con sorteo como incentivo.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => ',jhghjg lhglhgl ljglhglh lhghgh lhghgh glhglhglhjg hglhgl glglhglkj',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 147,
                    'name' => 'Calcula la huella de carbono del evento con una metodología reconocida (GHG Protocol o ISO 14064).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'ljglhgklhj glkjlkjgklj lkjlkjklj lkjbkl  vbn vbn vbn',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 148,
                    'name' => 'Compensa la huella de carbono del evento a través de proyectos certificados.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'jhgkjg lkjglkjg lhjglglhjg lhjgljglkj lkjglkjglkgj',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 149,
                    'name' => 'Calcula y compensa a cada asistente su huella de carbono individual (desplazamiento, alojamiento, restauración) para fomentar la responsabilidad personal.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'fsgnsfnstrgnsgngf ñlhsdlkhv -ñlj ´ñlj´ñlj´ñlñj´ñlj´kñlj ´kjklj-lkj -lnm-,.n ,mn',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 151,
                    'name' => 'Publica un informe de sostenibilidad tras el evento y haz una revisión interna con la dirección documentando lecciones aprendidas.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'cbn dgh dghdghn ,jhvhjvhjg ,kjblkhkhgb ,kjglhjglhjgklj  ,kjhgljhglkj',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 177,
                    'name' => 'Establece un protocolo de emergencia y evacuación adaptado al aforo, con vías señalizadas, rutas para vehículos de emergencia y coordinación con servicios externos.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'ñiugljkglkj ñklhlkhñlk ñlk lkjbglhjbkjhb hjhkj kjhñln .lkñlk hlkj ñlkj',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 190,
                    'name' => 'Implementa un protocolo contra el acoso y la discriminación, con canal de denuncia confidencial.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'vbv cv vxnxngfxnnj  lkjhlkjj kjhkjhkj hñkjhkjh lkjhkljhlkjh kljhkljh kjh',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 198,
                    'name' => 'Ofrece a los asistentes la opción de elegir entre recibir el obsequio del evento o donar su valor equivalente a una organización benéfica local.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'cnxfgnfgngfngfn sf sfnfsgnfgnfg zdfbzdbfg gf fg fg fg',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 3,
                    'name' => 'En la oficina, contrata electricidad de origen 100% renovable.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'fg dfndhyn mhgfkjshbln dlkjblkjbldkjbkjbdn lkj dñkjbñkjbdñkjbñkdjbñkjd',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 4,
                    'name' => 'En la oficina, cambia bombillas tradicionales por LED e instala sensores de presencia y luz natural.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => true,
                    'isCritical' => false,
                    'observations' => 'fgndfnfgnfgnndhndfgn kuhyfkjhv ,hjglkjlkj kjhkjhñkjhñlk hñlkhñlkhñlk',
                    'actionTaken' => 'aergaerhsrethstrh',
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 5,
                    'name' => 'En la oficina, fija la calefacción a un máximo de 19ºC y el aire acondicionado a un mínimo de 27ºC.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'bnmcmchjcghmghmgf ,jhg jlhgljk lkjhl kjhlkjhlk jkjg kjgh.lk',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 6,
                    'name' => 'En la oficina, imprime solo lo imprescindible, en modo ahorro y a doble cara, con papel reciclado.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'xfgbdfbdfbsgfgtsh kghfkjhfjhvj kbkñjhkjh kjhñkjh ñkjlhkñjh ñlkjlklkn lkk-l',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 7,
                    'name' => 'En la oficina, instala puntos de separación de residuos (orgánico, papel, envases).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'strhsfn wg gtr jhgjlhglkjh kjhkjhlkjh ljkhkjhgkjgkñj hñjhñjhkjh',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 158,
                    'name' => 'Ofrece la programación en formatos accesibles (subtítulos, lengua de signos, audiodescripción), con interpretación o subtitulado en directo en las sesiones principales.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'xvbvndghndghndghm .kjg lkj.kjh lkjhkj hñkjlh ñlkjhlk',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
            ],
        ],
        'RODAJE ELABORADO' => [
            'protocolCode' => 'be-green-my-film',
            'measures' => [
                [
                    'sortOrder' => 8,
                    'name' => 'Realiza un inventario de consumo energético antes del rodaje por departamento.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'No se realizará un inventario de consumo energético antes del rodaje por departamento porque no hya tiempo para prepararlo',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 9,
                    'name' => 'Registra el consumo energético de oficinas, localizaciones y vehículos eléctricos.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Tendremos en rodaje a un ECO PA para recopilar todos los datos eléctricos',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 11,
                    'name' => 'Usa electricidad de la red de distribución eléctrica (mínimo 50% del rodaje).',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'Lamentablemente trabajaremos en un espacio natural y no hay conexión de red.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 14,
                    'name' => 'Utiliza acumuladores de energía en vez de grupos electrógenos.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'Por problemas de presupuesto, no podremos utilizar acumuladores d energía, pero usaremos un grupo electrógeno con diesel 100% renovable.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 16,
                    'name' => 'Usa grupos electrógenos Stage V con diesel 100% renovable (mínimo 50% del rodaje).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Sí, usaremos un grupo electrógeno Stage III (no Stage V) con diesel 100% renovable.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 17,
                    'name' => 'Registra los consumos de combustible de los grupos electrógenos.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Sí, el ECO PA en rodaje recogerá el consumo de combustible del grupo.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 18,
                    'name' => 'Usa luz natural como fuente principal de iluminación (mínimo 50% del rodaje).',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'Aunque el rodaje será en exteriores en el Parque natural de Arganda, no podremos trabajar con luz natural ya que tendremos que reforzar con HMI',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 19,
                    'name' => 'Utiliza luces LED en el rodaje (mínimo 50%).',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'Al trabajar en exteriores no es posible trabajar con luces LED',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 26,
                    'name' => 'Prioriza alojamientos a menos de 10km del rodaje.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'No, el parque natural donde se va a rodar está bastante lejano y preferimos que los creativos de agencia, el director y los clientes se alojen en Madrid para así poder centralizar sus recogidas y que dispongan de una mejor comunicación cuando termine el rodaje.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 28,
                    'name' => 'Selecciona alojamientos con certificado de sostenibilidad o planes ambientales documentados.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Sí, buscaremos hoteels que tengan políticas de sostenibilidad',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 30,
                    'name' => 'Registra las pernoctaciones en alojamientos contratados por la productora.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'El ECO PA recogerá todo el rooming de director, agencia y clientes.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 31,
                    'name' => 'Elabora un plan de transporte con rutas, vehículos y objetivos de reducción de emisiones.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Se va a elaborar un plan de transportes para usar vans compartidas.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 32,
                    'name' => 'Procura que las localizaciones estén cercanas entre sí.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Vamos a solucionar en la misma localización varios sets.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 33,
                    'name' => 'Contrata personal y equipamiento local para reducir gastos de viaje.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Sí, la gran mayoría del equipo técnico es local, excepto el director. Como es un service, agencia y cliente son internacionales.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 38,
                    'name' => 'Registra el consumo de combustible y la distancia recorrida en todos los desplazamientos.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Sí, nuestro ECO MAnager recogerá todos los datos de los desplazmainetos de personal y material.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 39,
                    'name' => 'Registra la distancia recorrida en viajes en autocar, tren y avión.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Sí, vamos a recopilar todos los datos de los viajes que se van a hacewr desde Australia y reiuno Unido. Y, si es posible, compensaremos la huella de carbono al comprar el bilete',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 40,
                    'name' => 'Establece una política de no vuelos para trayectos de menos de 4 horas en tren.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Se establecerá una política de no vuelos para trayectos de menos de 4 horas en tren, pero no tenemos ninguno',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 41,
                    'name' => 'Prioriza el tren y el autobús frente al avión.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Sí, pero lamentablemnet tanto director como agencia y cliente vienne de UK y Australia',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 44,
                    'name' => 'Alquila vehículos eléctricos y/o híbridos con etiqueta 0, ECO o Euro 6.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Sí, al tener una sola localización, vamos a tener la mitad de las vans (2 de 4) electricas.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 45,
                    'name' => 'Reposta diesel 100% renovable en los vehículos de producción.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'La mitad de las vans (2 de 4) serán diesel y se intentará repostar comn diesel 100% renovable',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 47,
                    'name' => 'Pide vehículos de bajas emisiones para taxis y VTC.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Tenemos cuneta de empresa con Cabift, que compensa todos sus viajes',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 53,
                    'name' => 'Fomenta el transporte público incluyendo líneas, paradas y tiempos en las órdenes de rodaje y mapas de localización.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Sí, pondremos opciones de transporte público, auqneu la localización estña mjuy alejada y es dificilllehar hasta allñi.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 54,
                    'name' => 'Pon a disposición del equipo transporte colectivo para traslados.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'producción pondrá a disposición del equipo las vans para poder kllegar hasta el set',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 56,
                    'name' => 'Provee agua en fuentes o dispensadores recargables y pide al equipo que traiga su propia botella.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Se proveerá agua en fuentes o dispensadores recargables y se pedirá al equipo que traiga su propia botella',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 59,
                    'name' => 'Registra el consumo de agua en escena (efectos de lluvia, red general, etc.).',
                    'isApplicable' => false,
                    'willImplement' => null,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'No tendremos efecto lluvia ni se usará agua en escena',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 63,
                    'name' => 'Compra maderas certificadas FSC o PEFC para la construcción de decorados.',
                    'isApplicable' => false,
                    'willImplement' => null,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'No hya construcción en madera de ningún tipo en tosdo el rodaje',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 64,
                    'name' => 'Registra los materiales usados (papel, pilas, madera, etc.).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'mediante el eco PA se registrarán los materiales usados (papel, pilas, madera, etc.)',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 65,
                    'name' => 'Planifica la reutilización de materiales desde la fase de diseño de decorados.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Sí, se planificará la reutilización de materiales desde la fase de diseño de decorados. Se va a construir un pantalán de hierro y, después de hablar con el espacio natural, se va a quedar instalado después del rodaje ¿economía circular?',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 66,
                    'name' => 'Prioriza el rodaje en localizaciones naturales en vez de construir decorados en plató.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Sí, vamos a rodar en un espacio natural con lo que evitamos construoir decorados',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 68,
                    'name' => 'Reutiliza materiales de otras producciones (decorados, atrezzo, vestuario, etc.).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Se van a reutilkizar la gran mayoría de vestuario y la totalidsad del atrezzo',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 77,
                    'name' => 'Prioriza el alquiler de vestuario frente a la compra y/o compra de segunda mano.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Se priorizará el alquiler de vestuario frente a la compra y/o compra de segunda mano',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 92,
                    'name' => 'Usa cubos de separación de residuos en el set (orgánica, vidrio, envases, papel y restos).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Al trabajar en un espacio natural, e usarán cubos de separación de residuos en el set (orgánica, envases y papel)',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 95,
                    'name' => 'Señaliza correctamente los puntos de separación de residuos y pon cartelería de sostenibilidad.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Se señalizarán correctamente los puntos de separación de residuos y se pondrá cartelería de sostenibilidad',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 96,
                    'name' => 'Pesa los residuos generados (orgánico, papel, envases, vidrio y restos).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Se pesarán los residuos generados (orgánico, papel, envases, vidrio y restos). medinte nuestro Eco PA',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 106,
                    'name' => 'Registra el consumo de comidas y bebidas por tipología, tanto en catering como en craft service.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Se registrará el consumo de comidas y bebidas por tipología, tanto en catering como en craft service',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 108,
                    'name' => 'Registra el consumo de botellas y dispensadores de agua.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Se registrará el consumo de botellas y dispensadores de agua mediant el Eco PA',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 110,
                    'name' => 'Prioriza proveedores de catering con política de sostenibilidad documentada o certificación.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'Trabajamos siempre con el mismo catering pero no sabemos si tiene alguna certificación, aunque procura ser muy sostebibvle',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 119,
                    'name' => 'Realiza un estudio de impacto ambiental antes del rodaje.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Intrntaremos hacer un plan con la gestiónd el parque y seguir sus consejos',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 125,
                    'name' => 'Elabora un plan de sostenibilidad con objetivos, medidas y responsables por departamento.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Se elaborará un plan de sostenibilidad con objetivos, medidas y responsables por departamento',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 128,
                    'name' => 'Elabora un informe final de sostenibilidad con datos de huella de carbono, residuos, logros y mejoras.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Se elaborará un informe final de sostenibilidad con datos de huella de carbono, residuos, logros y mejoras',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 130,
                    'name' => 'Contrata un Eco PA en rodaje para implementar medidas y realizar la toma de datos.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => true,
                    'observations' => 'Sí, se contratará un Eco PA en rodaje para implementar medidas y realizar la toma de datos',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 137,
                    'name' => 'Aplica a las certificaciones verdes disponibles en el mercado.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'No vamos a aplicar a ninguna certificación, a no ser que lo pida expreamente eñlcliente',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 140,
                    'name' => 'Analiza los costes incurridos y los ahorros obtenidos al implementar medidas de sostenibilidad.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'No se analizarán los costes incurridos y los ahorros obtenidos al implementar medidas de sostenibilidad',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 144,
                    'name' => 'Analiza el impacto ambiental del guion en preproducción y busca alternativas narrativas.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'No se analizará el impacto ambiental del guion en preproducción ni se buscarán alternativas narrativas porque la,agencia no quiuere',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 146,
                    'name' => 'Fomenta acciones o conductas sostenibles en pantalla.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'El cliente ni la agencia quieren que nadie pueda tocar los contenidos del spot',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 172,
                    'name' => 'Promueve un ambiente inclusivo que celebre la diversidad cultural, de género y orientación.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Se promoverá un ambiente inclusivo que celebre la diversidad cultural, de género y orientación',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 3,
                    'name' => 'En la oficina, contrata electricidad de origen 100% renovable.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'No se contratará electricidad de origen 100% renovable en la oficina',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 4,
                    'name' => 'En la oficina, instala puntos de separación de residuos (orgánico, papel y envases).',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'la oficina dspone de cubos de separación de residuos',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 5,
                    'name' => 'En la oficina, fija la calefacción a un máximo de 19 ºC y el aire acondicionado a un mínimo de 27 ºC.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Producción programa los termóstatos en 19 ºC (calefacción) y 27 ºC (refrigeración) con bloqueo o clave, configura el apagado automático fuera del horario laboral y comunica la medida al equipo de oficina con un cartel junto al termostato.',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 6,
                    'name' => 'En la oficina, cambia las bombillas tradicionales por LED e instala sensores de presencia y luz natural.',
                    'isApplicable' => true,
                    'willImplement' => false,
                    'implemented' => null,
                    'isCritical' => null,
                    'observations' => 'La oficina es de alquiler y o podemos cambiar las bombilass ni poner detectoress de presencia',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
                [
                    'sortOrder' => 7,
                    'name' => 'En la oficina, imprime solo lo imprescindible, en modo ahorro y a doble cara, con papel reciclado.',
                    'isApplicable' => true,
                    'willImplement' => true,
                    'implemented' => null,
                    'isCritical' => false,
                    'observations' => 'Sí, se intenta imprimir lo menos posible y recuperar las impresiones mal realiadas',
                    'actionTaken' => null,
                    'executionIncident' => null,
                    'hasEvidence' => false,
                ],
            ],
        ],
    ];
}
