server {
    listen 80;
    server_name _;
    root /app/public;
    index index.php index.html;
    client_max_body_size 32m;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_index index.php;
        fastcgi_pass php:9000;
        fastcgi_read_timeout 180s;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }

    location ~* \.(?:env|ini|log|sql|sh|yml|yaml|twig|md|lock)$ {
        deny all;
    }
}
